In [17]:
x= np.array([
    [1,2],
    [3,4]
],dtype=np.float64)
print(x)

[[1. 2.]
 [3. 4.]]


In [18]:
y=np.array([
    [5,6]
    ,[7,8]
],dtype=np.float64)

print(y)

[[5. 6.]
 [7. 8.]]


In [20]:
print(x+y)
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [21]:
print(x*y)
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [22]:
u= np.array([9,10])
v= np.array([11,12])
print(u*v)

[ 99 120]


In [28]:
print(np.dot(u,v))

219


In [29]:
print(np.dot(x,u))

[29. 67.]


In [32]:
print(np.sum(x,axis=0))

[4. 6.]


In [33]:
print(np.sum(x,axis=1))

[3. 7.]


In [34]:
print(x.T)

[[1. 3.]
 [2. 4.]]


In [35]:
a = np.array({
    [1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]
})
b = np.array([21,22,23,24])
print(a+b)

TypeError: unhashable type: 'list'